exports.config = require('./config')
exports.service = require('./service')
exports.actions = require('./actions')
exports.updater = require('./updater')
exports.epic = require('./epic')
Object.assign(exports, require('./getters'))
Object.assign(exports, require('./components'))
Object.assign(exports, require('./hoc'))
Object.assign(exports, require('./hooks'))
